from .optimizer import TextualGradientDescent, Optimizer, TextualGradientDescentwithMomentum
from .optimizer_v2 import TextualGradientDescent as TextualGradientDescent_v2
from .optimizer_v2 import Optimizer as Optimizer_v2
from .optimizer_v2 import TextualGradientDescentwithMomentum as TextualGradientDescentwithMomentum_v2

TGD = TextualGradientDescent
TGD_v2 = TextualGradientDescent_v2
